### ISSUE TITLE
togglepower and togglecolor not working with multiple bulbs

### ISSUE THREAD

**Issue by Nyrt** [riplatt/LIFX-Touch-Switch#2]
The functions togglePower and toggleColor do not seem to work when there are multiple bulbs in the vector (implying that setColor and setPower may have issues). They function normally if only one bulb is in the vector, and the functions _are_ called once for each bulb in the vector, but it seems to have no effect on the bulbs.

Do you have any ideas what might be causing this? I've spent quite some time digging through the code to no avail.

**Comment by Nyrt** [comment]
Ah I see, this appears to be fixed in the dev branch. Taking a look at that now.

**Comment by riplatt** [comment]
Hey Nyrt, I'm currently working on a Dimmer Switch a clone of this code. you can find it at [LIFX-Dimmer-Switch](https://github.com/riplatt/LIFX-Dimmer-Switch).

Still having issues with not all the bulbs getting the same commands and getting out of sync, will have to implement some kind of sync check or command check still thinking about this, feel free to share what you code up.

**Comment by Nyrt** [comment]
Oh awesome, thanks! I'm personally working on something that'll let me trigger various effects through the amazon echo api (or other webhooks). I'm pretty much directly copying your stuff for the packet construction, so I'd be more than happy to share whatever I come up with.
